//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Predio", Namespace="http://schemas.datacontract.org/2004/07/ServicioTerreno.Model")]
    public partial class Predio : object
    {
        
        private int IdPredioField;
        
        private ServiceReference1.Manzana[] ManzanaField;
        
        private string NombreField;
        
        private string UbicacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPredio
        {
            get
            {
                return this.IdPredioField;
            }
            set
            {
                this.IdPredioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Manzana[] Manzana
        {
            get
            {
                return this.ManzanaField;
            }
            set
            {
                this.ManzanaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubicacion
        {
            get
            {
                return this.UbicacionField;
            }
            set
            {
                this.UbicacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Manzana", Namespace="http://schemas.datacontract.org/2004/07/ServicioTerreno.Model")]
    public partial class Manzana : object
    {
        
        private int IdManzanaField;
        
        private int IdPredioField;
        
        private ServiceReference1.Lote[] LoteField;
        
        private int NoManzanaField;
        
        private ServiceReference1.Predio PredioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdManzana
        {
            get
            {
                return this.IdManzanaField;
            }
            set
            {
                this.IdManzanaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPredio
        {
            get
            {
                return this.IdPredioField;
            }
            set
            {
                this.IdPredioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Lote[] Lote
        {
            get
            {
                return this.LoteField;
            }
            set
            {
                this.LoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoManzana
        {
            get
            {
                return this.NoManzanaField;
            }
            set
            {
                this.NoManzanaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Predio Predio
        {
            get
            {
                return this.PredioField;
            }
            set
            {
                this.PredioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lote", Namespace="http://schemas.datacontract.org/2004/07/ServicioTerreno.Model")]
    public partial class Lote : object
    {
        
        private ServiceReference1.Contrato ContratoField;
        
        private System.Nullable<int> IdContratoField;
        
        private int IdLoteField;
        
        private int IdManzanaField;
        
        private ServiceReference1.Manzana ManzanaField;
        
        private string NoLoteField;
        
        private double SuperficieField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Contrato Contrato
        {
            get
            {
                return this.ContratoField;
            }
            set
            {
                this.ContratoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdContrato
        {
            get
            {
                return this.IdContratoField;
            }
            set
            {
                this.IdContratoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLote
        {
            get
            {
                return this.IdLoteField;
            }
            set
            {
                this.IdLoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdManzana
        {
            get
            {
                return this.IdManzanaField;
            }
            set
            {
                this.IdManzanaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Manzana Manzana
        {
            get
            {
                return this.ManzanaField;
            }
            set
            {
                this.ManzanaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoLote
        {
            get
            {
                return this.NoLoteField;
            }
            set
            {
                this.NoLoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Superficie
        {
            get
            {
                return this.SuperficieField;
            }
            set
            {
                this.SuperficieField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contrato", Namespace="http://schemas.datacontract.org/2004/07/ServicioTerreno.Model")]
    public partial class Contrato : object
    {
        
        private double CostoField;
        
        private System.Nullable<System.DateTime> FechaContratoField;
        
        private int IdClienteField;
        
        private int IdContratoField;
        
        private System.Nullable<int> IdVendedorField;
        
        private ServiceReference1.Lote[] LoteField;
        
        private ServiceReference1.Pago[] PagoField;
        
        private ServiceReference1.Persona PersonaField;
        
        private ServiceReference1.Persona Persona1Field;
        
        private string Testigo1Field;
        
        private string Testigo2Field;
        
        private int TipoFechaField;
        
        private string TipoPagoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Costo
        {
            get
            {
                return this.CostoField;
            }
            set
            {
                this.CostoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaContrato
        {
            get
            {
                return this.FechaContratoField;
            }
            set
            {
                this.FechaContratoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente
        {
            get
            {
                return this.IdClienteField;
            }
            set
            {
                this.IdClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdContrato
        {
            get
            {
                return this.IdContratoField;
            }
            set
            {
                this.IdContratoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdVendedor
        {
            get
            {
                return this.IdVendedorField;
            }
            set
            {
                this.IdVendedorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Lote[] Lote
        {
            get
            {
                return this.LoteField;
            }
            set
            {
                this.LoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Pago[] Pago
        {
            get
            {
                return this.PagoField;
            }
            set
            {
                this.PagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Persona Persona
        {
            get
            {
                return this.PersonaField;
            }
            set
            {
                this.PersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Persona Persona1
        {
            get
            {
                return this.Persona1Field;
            }
            set
            {
                this.Persona1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Testigo1
        {
            get
            {
                return this.Testigo1Field;
            }
            set
            {
                this.Testigo1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Testigo2
        {
            get
            {
                return this.Testigo2Field;
            }
            set
            {
                this.Testigo2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoFecha
        {
            get
            {
                return this.TipoFechaField;
            }
            set
            {
                this.TipoFechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPago
        {
            get
            {
                return this.TipoPagoField;
            }
            set
            {
                this.TipoPagoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/ServicioTerreno.Model")]
    public partial class Persona : object
    {
        
        private string ApellidoMaternoField;
        
        private string ApellidoPaternoField;
        
        private ServiceReference1.Contrato[] ContratoField;
        
        private ServiceReference1.Contrato[] Contrato1Field;
        
        private string CorreoField;
        
        private string DireccionField;
        
        private int IdPersonaField;
        
        private string NombreField;
        
        private string TelefonoField;
        
        private ServiceReference1.Usuario[] UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno
        {
            get
            {
                return this.ApellidoMaternoField;
            }
            set
            {
                this.ApellidoMaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno
        {
            get
            {
                return this.ApellidoPaternoField;
            }
            set
            {
                this.ApellidoPaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Contrato[] Contrato
        {
            get
            {
                return this.ContratoField;
            }
            set
            {
                this.ContratoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Contrato[] Contrato1
        {
            get
            {
                return this.Contrato1Field;
            }
            set
            {
                this.Contrato1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPersona
        {
            get
            {
                return this.IdPersonaField;
            }
            set
            {
                this.IdPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Usuario[] Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pago", Namespace="http://schemas.datacontract.org/2004/07/ServicioTerreno.Model")]
    public partial class Pago : object
    {
        
        private double CantidadPagoField;
        
        private ServiceReference1.Contrato ContratoField;
        
        private System.DateTime FechaPagoField;
        
        private int IdContratoField;
        
        private int IdPagoField;
        
        private int IdTipoPagoField;
        
        private string SerialPagoField;
        
        private ServiceReference1.TipoPago TipoPagoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CantidadPago
        {
            get
            {
                return this.CantidadPagoField;
            }
            set
            {
                this.CantidadPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Contrato Contrato
        {
            get
            {
                return this.ContratoField;
            }
            set
            {
                this.ContratoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPago
        {
            get
            {
                return this.FechaPagoField;
            }
            set
            {
                this.FechaPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdContrato
        {
            get
            {
                return this.IdContratoField;
            }
            set
            {
                this.IdContratoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPago
        {
            get
            {
                return this.IdPagoField;
            }
            set
            {
                this.IdPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoPago
        {
            get
            {
                return this.IdTipoPagoField;
            }
            set
            {
                this.IdTipoPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialPago
        {
            get
            {
                return this.SerialPagoField;
            }
            set
            {
                this.SerialPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TipoPago TipoPago
        {
            get
            {
                return this.TipoPagoField;
            }
            set
            {
                this.TipoPagoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPago", Namespace="http://schemas.datacontract.org/2004/07/ServicioTerreno.Model")]
    public partial class TipoPago : object
    {
        
        private string DescripcionField;
        
        private int IdTipoPagoField;
        
        private ServiceReference1.Pago[] PagoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoPago
        {
            get
            {
                return this.IdTipoPagoField;
            }
            set
            {
                this.IdTipoPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Pago[] Pago
        {
            get
            {
                return this.PagoField;
            }
            set
            {
                this.PagoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/ServicioTerreno.Model")]
    public partial class Usuario : object
    {
        
        private string ContraseñaField;
        
        private int IdPersonaField;
        
        private int IdUsuarioField;
        
        private ServiceReference1.Persona PersonaField;
        
        private string Usuario1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña
        {
            get
            {
                return this.ContraseñaField;
            }
            set
            {
                this.ContraseñaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPersona
        {
            get
            {
                return this.IdPersonaField;
            }
            set
            {
                this.IdPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario
        {
            get
            {
                return this.IdUsuarioField;
            }
            set
            {
                this.IdUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Persona Persona
        {
            get
            {
                return this.PersonaField;
            }
            set
            {
                this.PersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario1
        {
            get
            {
                return this.Usuario1Field;
            }
            set
            {
                this.Usuario1Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarPredio", ReplyAction="http://tempuri.org/IService1/RegistrarPredioResponse")]
        System.Threading.Tasks.Task<bool> RegistrarPredioAsync(ServiceReference1.Predio predio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarManzana", ReplyAction="http://tempuri.org/IService1/RegistrarManzanaResponse")]
        System.Threading.Tasks.Task<bool> RegistrarManzanaAsync(ServiceReference1.Manzana manzana);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarLote", ReplyAction="http://tempuri.org/IService1/RegistrarLoteResponse")]
        System.Threading.Tasks.Task<bool> RegistrarLoteAsync(ServiceReference1.Lote lote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarContrato", ReplyAction="http://tempuri.org/IService1/RegistrarContratoResponse")]
        System.Threading.Tasks.Task<bool> RegistrarContratoAsync(ServiceReference1.Contrato contrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarPago", ReplyAction="http://tempuri.org/IService1/RegistrarPagoResponse")]
        System.Threading.Tasks.Task<bool> RegistrarPagoAsync(ServiceReference1.Pago pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarPersona", ReplyAction="http://tempuri.org/IService1/RegistrarPersonaResponse")]
        System.Threading.Tasks.Task<bool> RegistrarPersonaAsync(ServiceReference1.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarPredio", ReplyAction="http://tempuri.org/IService1/ModificarPredioResponse")]
        System.Threading.Tasks.Task<bool> ModificarPredioAsync(ServiceReference1.Predio predio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarManzana", ReplyAction="http://tempuri.org/IService1/ModificarManzanaResponse")]
        System.Threading.Tasks.Task<bool> ModificarManzanaAsync(ServiceReference1.Manzana manzana);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarLote", ReplyAction="http://tempuri.org/IService1/ModificarLoteResponse")]
        System.Threading.Tasks.Task<bool> ModificarLoteAsync(ServiceReference1.Lote lote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarContratoLote", ReplyAction="http://tempuri.org/IService1/ModificarContratoLoteResponse")]
        System.Threading.Tasks.Task<bool> ModificarContratoLoteAsync(int IdContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarContrato", ReplyAction="http://tempuri.org/IService1/ModificarContratoResponse")]
        System.Threading.Tasks.Task<bool> ModificarContratoAsync(ServiceReference1.Contrato contrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarPago", ReplyAction="http://tempuri.org/IService1/ModificarPagoResponse")]
        System.Threading.Tasks.Task<bool> ModificarPagoAsync(ServiceReference1.Pago pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarPersona", ReplyAction="http://tempuri.org/IService1/ModificarPersonaResponse")]
        System.Threading.Tasks.Task<bool> ModificarPersonaAsync(ServiceReference1.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarPredio", ReplyAction="http://tempuri.org/IService1/EliminarPredioResponse")]
        System.Threading.Tasks.Task<bool> EliminarPredioAsync(int idPredio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarManzana", ReplyAction="http://tempuri.org/IService1/EliminarManzanaResponse")]
        System.Threading.Tasks.Task<bool> EliminarManzanaAsync(int idManzana);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarLote", ReplyAction="http://tempuri.org/IService1/EliminarLoteResponse")]
        System.Threading.Tasks.Task<bool> EliminarLoteAsync(int idLote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarContrato", ReplyAction="http://tempuri.org/IService1/EliminarContratoResponse")]
        System.Threading.Tasks.Task<bool> EliminarContratoAsync(int idContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarPago", ReplyAction="http://tempuri.org/IService1/EliminarPagoResponse")]
        System.Threading.Tasks.Task<bool> EliminarPagoAsync(int idPago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarPersona", ReplyAction="http://tempuri.org/IService1/EliminarPersonaResponse")]
        System.Threading.Tasks.Task<bool> EliminarPersonaAsync(int idPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarPredio", ReplyAction="http://tempuri.org/IService1/ListarPredioResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Predio[]> ListarPredioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarManzana", ReplyAction="http://tempuri.org/IService1/ListarManzanaResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Manzana[]> ListarManzanaAsync(int IdPredio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarLoteManzana", ReplyAction="http://tempuri.org/IService1/ListarLoteManzanaResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Lote[]> ListarLoteManzanaAsync(int IdManzana);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarLoteContrato", ReplyAction="http://tempuri.org/IService1/ListarLoteContratoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Lote[]> ListarLoteContratoAsync(int IdContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarContrato", ReplyAction="http://tempuri.org/IService1/ListarContratoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Contrato[]> ListarContratoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarContrato", ReplyAction="http://tempuri.org/IService1/BuscarContratoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Contrato> BuscarContratoAsync(int IdContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarPago", ReplyAction="http://tempuri.org/IService1/ListarPagoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Pago[]> ListarPagoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarPagoContrato", ReplyAction="http://tempuri.org/IService1/ListarPagoContratoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Pago[]> ListarPagoContratoAsync(int IdContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarPersona", ReplyAction="http://tempuri.org/IService1/ListarPersonaResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Persona[]> ListarPersonaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarTipoPago", ReplyAction="http://tempuri.org/IService1/ListarTipoPagoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.TipoPago[]> ListarTipoPagoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Usuario> LoginAsync(string usuario, string contraseña);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IService1Channel : ServiceReference1.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference1.IService1>, ServiceReference1.IService1
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarPredioAsync(ServiceReference1.Predio predio)
        {
            return base.Channel.RegistrarPredioAsync(predio);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarManzanaAsync(ServiceReference1.Manzana manzana)
        {
            return base.Channel.RegistrarManzanaAsync(manzana);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarLoteAsync(ServiceReference1.Lote lote)
        {
            return base.Channel.RegistrarLoteAsync(lote);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarContratoAsync(ServiceReference1.Contrato contrato)
        {
            return base.Channel.RegistrarContratoAsync(contrato);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarPagoAsync(ServiceReference1.Pago pago)
        {
            return base.Channel.RegistrarPagoAsync(pago);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarPersonaAsync(ServiceReference1.Persona persona)
        {
            return base.Channel.RegistrarPersonaAsync(persona);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarPredioAsync(ServiceReference1.Predio predio)
        {
            return base.Channel.ModificarPredioAsync(predio);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarManzanaAsync(ServiceReference1.Manzana manzana)
        {
            return base.Channel.ModificarManzanaAsync(manzana);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarLoteAsync(ServiceReference1.Lote lote)
        {
            return base.Channel.ModificarLoteAsync(lote);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarContratoLoteAsync(int IdContrato)
        {
            return base.Channel.ModificarContratoLoteAsync(IdContrato);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarContratoAsync(ServiceReference1.Contrato contrato)
        {
            return base.Channel.ModificarContratoAsync(contrato);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarPagoAsync(ServiceReference1.Pago pago)
        {
            return base.Channel.ModificarPagoAsync(pago);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarPersonaAsync(ServiceReference1.Persona persona)
        {
            return base.Channel.ModificarPersonaAsync(persona);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarPredioAsync(int idPredio)
        {
            return base.Channel.EliminarPredioAsync(idPredio);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarManzanaAsync(int idManzana)
        {
            return base.Channel.EliminarManzanaAsync(idManzana);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarLoteAsync(int idLote)
        {
            return base.Channel.EliminarLoteAsync(idLote);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarContratoAsync(int idContrato)
        {
            return base.Channel.EliminarContratoAsync(idContrato);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarPagoAsync(int idPago)
        {
            return base.Channel.EliminarPagoAsync(idPago);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarPersonaAsync(int idPersona)
        {
            return base.Channel.EliminarPersonaAsync(idPersona);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Predio[]> ListarPredioAsync()
        {
            return base.Channel.ListarPredioAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Manzana[]> ListarManzanaAsync(int IdPredio)
        {
            return base.Channel.ListarManzanaAsync(IdPredio);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Lote[]> ListarLoteManzanaAsync(int IdManzana)
        {
            return base.Channel.ListarLoteManzanaAsync(IdManzana);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Lote[]> ListarLoteContratoAsync(int IdContrato)
        {
            return base.Channel.ListarLoteContratoAsync(IdContrato);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Contrato[]> ListarContratoAsync()
        {
            return base.Channel.ListarContratoAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Contrato> BuscarContratoAsync(int IdContrato)
        {
            return base.Channel.BuscarContratoAsync(IdContrato);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Pago[]> ListarPagoAsync()
        {
            return base.Channel.ListarPagoAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Pago[]> ListarPagoContratoAsync(int IdContrato)
        {
            return base.Channel.ListarPagoContratoAsync(IdContrato);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Persona[]> ListarPersonaAsync()
        {
            return base.Channel.ListarPersonaAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TipoPago[]> ListarTipoPagoAsync()
        {
            return base.Channel.ListarTipoPagoAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Usuario> LoginAsync(string usuario, string contraseña)
        {
            return base.Channel.LoginAsync(usuario, contraseña);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:57542/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
